name: Scrape latest deals

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *' # every day at 8am

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest deals data
      run: |-
        curl -s "https://www.cheapshark.com/api/1.0/deals" > deals.json
    - name: Fetch latest wishlist data
      run: |-
        curl -s "https://store.steampowered.com/wishlist/id/jmperafan/wishlistdata/
" > wishlist.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push