name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *' # every day at 8am

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest deals data
      run: |-
        curl -s "https://www.cheapshark.com/api/1.0/deals" > "$(date +%F)deals.json"
    - name: Fetch latest wishlist data
      run: |-
        curl -s "https://store.steampowered.com/wishlist/id/jmperafan/wishlistdata" > wishlist.json

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_BUCKET }}'

    - id: 'upload-file-deals'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '.'
        destination: 'cheapshark'